name: Node.js CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit & Integration Tests
        run: npm test

      - name: Display Jest Test Report
        if: always()
        run: |
          echo "---- TEST REPORT ----"
          cat ./jest-report.log || echo "No report found"
